const JSON_HEADERS = {
  "content-type": "application/json; charset=utf-8",
  "cache-control": "no-store"
};
const API_PREFIX = "/api/giae";
const R2_BINDINGS = ["GIAE_PROJECT_BACKUPS", "GIAE_PROJECT_DOCUMENTS", "GIAE_BRAND_ASSETS", "GIAE_FIELD_MEDIA"];
function json(data, init = {}){ return new Response(JSON.stringify(data, null, 2), { status: init.status || 200, headers: { ...JSON_HEADERS, ...(init.headers || {}) } }); }
function text(message, status = 404){ return new Response(message, { status, headers: { "content-type": "text/plain; charset=utf-8" } }); }
async function readJson(request){ const textBody = await request.text(); if(!textBody) return {}; try{ return JSON.parse(textBody); }catch{ throw new Error("JSON invalido"); } }
function now(){ return new Date().toISOString(); }
function id(prefix){ return prefix + "-" + crypto.randomUUID(); }
function hasBinding(env, name){ return Boolean(env && env[name]); }
function hasDb(env){ return hasBinding(env, "GIAE_DB"); }
function envStatus(env){ return { d1: hasDb(env), r2: Object.fromEntries(R2_BINDINGS.map(name => [name, hasBinding(env, name)])), assets: hasBinding(env, "ASSETS"), authTokenConfigured: Boolean(env?.GIAE_API_TOKEN), environment: env?.GIAE_ENV || "production" }; }
async function sha256Hex(textValue){ const input = new TextEncoder().encode(textValue); const digest = await crypto.subtle.digest("SHA-256", input); return Array.from(new Uint8Array(digest)).map(byte => byte.toString(16).padStart(2, "0")).join(""); }
function requireWriteAuth(request, env){ if(!env?.GIAE_API_TOKEN) return { ok: false, response: json({ ok: false, error: "GIAE_API_TOKEN no configurado como secreto del Worker. Escritura bloqueada por seguridad." }, { status: 503 }) }; const header = request.headers.get("authorization") || ""; const token = header.startsWith("Bearer ") ? header.slice(7).trim() : ""; if(token !== env.GIAE_API_TOKEN) return { ok: false, response: json({ ok: false, error: "No autorizado" }, { status: 401 }) }; return { ok: true }; }
async function audit(env, event = {}){ if(!hasDb(env)) return null; const auditId = event.id || id("audit"); await env.GIAE_DB.prepare(`INSERT INTO audit_events (id, company_id, project_id, user_id, action, detail_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)`).bind(auditId, event.companyId || "local-company", event.projectId || null, event.userId || null, event.action || "evento", JSON.stringify(event.detail || {}), event.createdAt || now()).run(); return auditId; }
async function health(request, env){ return json({ ok: true, service: "GIAE Worker API", schema: "giae.worker.health.v1", generatedAt: now(), apiBase: API_PREFIX, bindings: envStatus(env), endpoints: ["GET /api/giae/health", "POST /api/giae/session/start", "POST /api/giae/license/check", "GET /api/giae/workspaces/:workspaceId", "GET /api/giae/projects/:projectId", "POST /api/giae/projects/:projectId/sync", "POST /api/giae/files/presign", "GET /api/giae/audit"] }); }
async function startSession(request, env){ const payload = await readJson(request); return json({ ok: true, schema: "giae.worker.session.v1", sessionId: id("session"), profile: payload.profile || "sin_perfil", authMode: env?.GIAE_API_TOKEN ? "token_worker" : "preparacion_local_sin_escritura", writeEnabled: Boolean(env?.GIAE_API_TOKEN), createdAt: now(), note: "Sesion tecnica inicial. La autenticacion real de usuarios se debe endurecer en Fase 6." }); }
async function licenseCheck(request, env){ const payload = await readJson(request); if(!hasDb(env)) return json({ ok: true, status: "preparacion_local", plan: payload.plan || "local-preparacion", seats: 1, source: "sin_d1" }); const companyId = payload.companyId || "local-company"; const row = await env.GIAE_DB.prepare(`SELECT * FROM licenses WHERE company_id = ? ORDER BY created_at DESC LIMIT 1`).bind(companyId).first(); return json({ ok: true, status: row?.status || "sin_licencia_activa", plan: row?.plan || "local-preparacion", seats: row?.seats || 1, validUntil: row?.valid_until || "", source: row ? "d1" : "fallback" }); }
async function workspaceRead(request, env, workspaceId){ if(!hasDb(env)) return json({ ok: true, workspace: { id: workspaceId, name: "GIAE Chile", mode: "sin_d1" }, users: [], roles: [] }); const company = await env.GIAE_DB.prepare(`SELECT * FROM companies WHERE id = ?`).bind(workspaceId).first(); const users = await env.GIAE_DB.prepare(`SELECT id, email, name, role_id, status, last_seen_at FROM users WHERE company_id = ? ORDER BY name`).bind(workspaceId).all(); const roles = await env.GIAE_DB.prepare(`SELECT id, name, permissions_json, status FROM roles WHERE company_id = ? OR company_id = 'global' ORDER BY name`).bind(workspaceId).all(); return json({ ok: true, workspace: company || { id: workspaceId, name: "Workspace no registrado" }, users: users.results || [], roles: roles.results || [] }); }
async function projectRead(request, env, projectId){ if(!hasDb(env)) return json({ ok: false, error: "D1 no configurado" }, { status: 503 }); const project = await env.GIAE_DB.prepare(`SELECT * FROM projects WHERE id = ?`).bind(projectId).first(); if(!project) return json({ ok: false, error: "Proyecto no encontrado" }, { status: 404 }); const revision = await env.GIAE_DB.prepare(`SELECT * FROM project_revisions WHERE project_id = ? ORDER BY created_at DESC LIMIT 1`).bind(projectId).first(); return json({ ok: true, project, latestRevision: revision || null }); }
async function syncProject(request, env, projectId){ const auth = requireWriteAuth(request, env); if(!auth.ok) return auth.response; if(!hasDb(env)) return json({ ok: false, error: "D1 no configurado" }, { status: 503 }); const payload = await readJson(request); const envelope = payload.envelope || payload; const project = envelope.projectSnapshot || envelope.project || {}; const companyId = envelope.companyId || project.companyId || "local-company"; const revisionId = id("rev"); const createdAt = now(); const serialized = JSON.stringify(envelope); const hash = await sha256Hex(serialized); const projectName = project.name || envelope.projectName || "Proyecto GIAE"; const status = project.status || "En desarrollo"; const backupKey = `projects/${projectId}/revisions/${revisionId}.giae.json`; await env.GIAE_DB.prepare(`INSERT INTO companies (id, name, status, created_at, updated_at) VALUES (?, ?, 'activo', ?, ?) ON CONFLICT(id) DO UPDATE SET name = COALESCE(excluded.name, companies.name), updated_at = excluded.updated_at`).bind(companyId, project.company || envelope.companyName || "GIAE Chile", createdAt, createdAt).run(); await env.GIAE_DB.prepare(`INSERT INTO projects (id, company_id, owner_user_id, name, status, meta_json, updated_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET name = excluded.name, status = excluded.status, meta_json = excluded.meta_json, updated_at = excluded.updated_at`).bind(projectId, companyId, envelope.authorUserId || null, projectName, status, JSON.stringify({ client: project.client || "", source: "sync" }), createdAt, createdAt).run(); await env.GIAE_DB.prepare(`INSERT INTO project_revisions (id, project_id, revision, hash, summary_json, author_user_id, r2_key, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).bind(revisionId, projectId, envelope.revision || 1, hash, JSON.stringify({ name: projectName, status, schema: envelope.schema || "giae.cloud.sync-envelope.v1" }), envelope.authorUserId || null, backupKey, createdAt).run(); if(env.GIAE_PROJECT_BACKUPS){ await env.GIAE_PROJECT_BACKUPS.put(backupKey, serialized, { httpMetadata: { contentType: "application/json; charset=utf-8" }, customMetadata: { projectId, revisionId, hash } }); await env.GIAE_DB.prepare(`INSERT INTO file_assets (id, project_id, kind, r2_binding, r2_key, sha256, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)`).bind(id("file"), projectId, "project_backup", "GIAE_PROJECT_BACKUPS", backupKey, hash, createdAt).run(); } await env.GIAE_DB.prepare(`INSERT INTO sync_queue (id, project_id, status, operation, payload_hash, created_at, processed_at) VALUES (?, ?, 'procesado', 'project.upsert', ?, ?, ?)`).bind(id("sync"), projectId, hash, createdAt, createdAt).run(); await audit(env, { companyId, projectId, userId: envelope.authorUserId || null, action: "project.sync", detail: { revisionId, hash, backupKey } }); return json({ ok: true, projectId, revisionId, hash, backupKey, r2Saved: Boolean(env.GIAE_PROJECT_BACKUPS) }); }
async function filePrepare(request, env){ const auth = requireWriteAuth(request, env); if(!auth.ok) return auth.response; const payload = await readJson(request); const projectId = payload.projectId || "sin-proyecto"; const kind = payload.kind || "documents"; const fileName = String(payload.fileName || "archivo.bin").replace(/[^a-z0-9._-]+/gi, "-"); const binding = kind === "brand" ? "GIAE_BRAND_ASSETS" : kind === "field_media" ? "GIAE_FIELD_MEDIA" : "GIAE_PROJECT_DOCUMENTS"; const key = `${kind}/${projectId}/${Date.now()}-${fileName}`; return json({ ok: true, binding, key, method: "PUT via Worker endpoint futuro", note: "No se entregan credenciales R2 al navegador." }); }
async function auditSearch(request, env){ if(!hasDb(env)) return json({ ok: false, error: "D1 no configurado" }, { status: 503 }); const url = new URL(request.url); const projectId = url.searchParams.get("projectId"); const limit = Math.min(Number(url.searchParams.get("limit") || 50), 100); const stmt = projectId ? env.GIAE_DB.prepare(`SELECT * FROM audit_events WHERE project_id = ? ORDER BY created_at DESC LIMIT ?`).bind(projectId, limit) : env.GIAE_DB.prepare(`SELECT * FROM audit_events ORDER BY created_at DESC LIMIT ?`).bind(limit); const rows = await stmt.all(); return json({ ok: true, results: rows.results || [] }); }
async function routeApi(request, env){ const url = new URL(request.url); const path = url.pathname; if(path === `${API_PREFIX}/health` && request.method === "GET") return health(request, env); if(path === `${API_PREFIX}/session/start` && request.method === "POST") return startSession(request, env); if(path === `${API_PREFIX}/license/check` && request.method === "POST") return licenseCheck(request, env); if(path.startsWith(`${API_PREFIX}/workspaces/`) && request.method === "GET") return workspaceRead(request, env, decodeURIComponent(path.split("/").pop() || "workspace-local")); if(path.startsWith(`${API_PREFIX}/projects/`) && path.endsWith("/sync") && request.method === "POST"){ const parts = path.split("/"); return syncProject(request, env, decodeURIComponent(parts[4] || "sin-proyecto")); } if(path.startsWith(`${API_PREFIX}/projects/`) && request.method === "GET") return projectRead(request, env, decodeURIComponent(path.split("/").pop() || "sin-proyecto")); if(path === `${API_PREFIX}/files/presign` && request.method === "POST") return filePrepare(request, env); if(path === `${API_PREFIX}/audit` && request.method === "GET") return auditSearch(request, env); return json({ ok: false, error: "Endpoint no encontrado", path, method: request.method }, { status: 404 }); }
export default { async fetch(request, env, ctx){ try{ const url = new URL(request.url); if(url.pathname.startsWith(`${API_PREFIX}/`)) return routeApi(request, env, ctx); if(env.ASSETS) return env.ASSETS.fetch(request); return text("GIAE Worker API activo. Binding ASSETS no configurado.", 200); }catch(error){ return json({ ok: false, error: error?.message || String(error) }, { status: 500 }); } } };